version: '3'

services:
  adminer:
    image: adminer:latest
    container_name: adminer_global
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - proxy-network
      - data-network

networks:
  proxy-network:
    external: true
  data-network:
    external: true